### ISSUE TITLE
api.rpc.router.getBestRoute not exposed?

### ISSUE THREAD

**Issue by sourabhniyogi** [parallel-finance/parallel-js#63]
We are trying to use the "getBestRoute" function in your README to add price valuation from the "parallel router" (at different prices, eg. $1, $10, $100, $1000), but missing some key steps for "npm" -- can you advise?
  
```
# cat testParallelPath.js 
const {
    ApiPromise,
    options,
    WsProvider,
    Keyring
} = require("@parallel-finance/api")

async function main() {
    const api = await ApiPromise.create(options({
        provider: new WsProvider()
    }))
    const [route, amount] = await api.rpc.router.getBestRoute("10000000", 101, 1, true);

    console.log(route, amount);
}

main()
    .then(() => {
        process.exit(0);
    })
    .catch((e) => {
        console.error('ERROR', e);
        process.exit(1);
    });

# node testParallelPath.js

ERROR TypeError: api.rpc.router.getBestRoute is not a function
    at main (/root/go/src/github.com/colorfulnotion/polkaholic/substrate/test/testParallelPath.js:14:50)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

# npm ls @parallel-finance/api
polkaholic@0.1.0 /root/go/src/github.com/colorfulnotion/polkaholic
└── @parallel-finance/api@1.7.13
```

**Comment by alannotnerd** [comment]
I use the code you pasted but I got the output
```
$ node index.js
2022-09-30 09:18:11        API/INIT: parallel/192: Not decorating unknown runtime apis: LoansApi/1, RouterApi/1
Type(2) [
  <BN: 65>,
  <BN: 1>,
  registry: TypeRegistry {},
  initialU8aLength: 0
] <BN: 14b>
```

**Comment by alannotnerd** [comment]
Can you do another try in a clean repo?

**Comment by sourabhniyogi** [comment]
Thank you for looking into it -- good idea, but no such luck:
```
# mkdir parallel2
# cd parallel2
# cp ../parallel/testParallelPath.js .
# yarn add @parallel-finance/api
yarn add v1.22.19
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 70 new dependencies.
info Direct dependencies
└─ @parallel-finance/api@1.7.13
info All dependencies
├─ @noble/hashes@1.1.2
├─ @noble/secp256k1@1.7.0
├─ @open-web3/orml-api-derive@1.1.4
├─ @open-web3/orml-type-definitions@1.1.4
├─ @open-web3/orml-types@1.1.4
├─ @parallel-finance/api@1.7.13
├─ @parallel-finance/type-definitions@1.7.13
├─ @parallel-finance/types@1.7.13
├─ @polkadot/api-derive@9.4.2
├─ @polkadot/api@9.4.2
├─ @polkadot/networks@10.1.9
├─ @polkadot/types-known@9.4.2
├─ @polkadot/types-support@9.4.2
├─ @polkadot/wasm-crypto-init@6.3.1
├─ @polkadot/wasm-crypto@6.3.1
├─ @polkadot/x-fetch@10.1.9
├─ @polkadot/x-randomvalues@10.1.9
├─ @polkadot/x-textdecoder@10.1.9
├─ @polkadot/x-textencoder@10.1.9
├─ @polkadot/x-ws@10.1.9
├─ @scure/base@1.1.1
├─ @substrate/connect-extension-protocol@1.0.1
├─ @substrate/connect@0.7.14
├─ @substrate/smoldot-light@0.6.34
├─ @substrate/ss58-registry@1.29.1
├─ @types/bn.js@5.1.1
├─ @types/node-fetch@2.6.2
├─ @types/websocket@1.0.5
├─ asynckit@0.4.0
├─ bn.js@5.2.1
├─ bufferutil@4.0.6
├─ combined-stream@1.0.8
├─ data-uri-to-buffer@4.0.0
├─ debug@4.3.4
├─ delayed-stream@1.0.0
├─ ed2curve@0.3.0
├─ es6-weak-map@2.0.3
├─ event-emitter@0.3.5
├─ ext@1.7.0
├─ fetch-blob@3.2.0
├─ form-data@3.0.1
├─ formdata-polyfill@4.0.10
├─ is-promise@2.2.2
├─ is-typedarray@1.0.0
├─ json-stringify-safe@5.0.1
├─ lodash.merge@4.6.2
├─ lodash@4.17.21
├─ lru-queue@0.1.0
├─ memoizee@0.4.15
├─ mime-db@1.52.0
├─ mime-types@2.1.35
├─ mock-socket@9.1.5
├─ ms@2.1.2
├─ next-tick@1.1.0
├─ nock@13.2.9
├─ node-domexception@1.0.0
├─ node-fetch@3.2.10
├─ pako@2.0.4
├─ propagate@2.0.1
├─ regenerator-runtime@0.13.9
├─ timers-ext@0.1.7
├─ tslib@2.4.0
├─ tweetnacl@1.0.3
├─ type@1.2.0
├─ typedarray-to-buffer@3.1.5
├─ utf-8-validate@5.0.9
├─ web-streams-polyfill@3.2.1
├─ websocket@1.0.34
├─ ws@8.9.0
└─ yaeti@0.0.6
Done in 8.03s.

# node testParallelPath.js 
ERROR TypeError: api.rpc.router.getBestRoute is not a function
    at main (/root/parallel2/testParallelPath.js:12:50)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

# npm ls
parallel2@ /root/parallel2
└── @parallel-finance/api@1.7.13

root@kusama:~/parallel2# node -v
v17.0.1
```
This is on an Ubuntu 20 node.

I also started with a different directory with just `npm install @parallel-finance/api` and got the same error

Usually with package conflicts there are tons of warnings.  
The router object is there, since:
```
console.log(api.rpc.router);
```
shows 
```
{}
```
so I think its about exposing `getBestRoute` in that router object?
